# Generated by Django 2.2.6 on 2019-12-18 17:16

from django.db import migrations, models
import format.validaters


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=150)),
                ('mod', models.FileField(upload_to='documents/', validators=[format.validaters.validate_file_extension])),
            ],
        ),
    ]
